import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../influ/index.html',import.meta.url),'utf8');
const source=html.match(/<script id="influ-app">([\s\S]*?)<\/script>/)[1];
function app(saved){const elements=new Map(),handlers={};
 function el(id){if(!elements.has(id))elements.set(id,{value:'',textContent:'',innerHTML:'',checked:false,hidden:false,handlers:{},addEventListener(n,fn){this.handlers[n]=fn},setAttribute(){},showModal(){this.open=true},close(){this.open=false},focus(){}});return elements.get(id)}
 for(const tag of html.matchAll(/<(?:input|select|textarea)[^>]*\bid="([^"]+)"[^>]*>/g)){const e=el(tag[1]);e.value=tag[0].match(/\bvalue="([^"]*)"/)?.[1]||'';e.checked=tag[0].includes(' checked')}
 const topics=['สิ่งแวดล้อม','ความยั่งยืน','ขยะ','ครู'].map(value=>({value,checked:true}));const tabs=['search','database','shortlist'].map(tab=>({dataset:{tab},setAttribute(){}}));
 const doc={getElementById:el,querySelectorAll(q){return q==='#topic-options input:checked'?topics.filter(e=>e.checked):q==='#topic-options input'?topics:q==='[data-tab]'?tabs:[]},querySelector(){return el('nav')},addEventListener(n,f){handlers[n]=f}};
 let raw=saved||null;const kv=new Map();if(saved)kv.set("cp-influencer-ux-v3",saved);
 const ctx=vm.createContext({document:doc,location:{host:"test.example"},URL,structuredClone,localStorage:{getItem(k){return kv.get(k)||null},setItem(k,v){kv.set(k,v);raw=v},removeItem(k){kv.delete(k)}},setTimeout(){return 1},clearTimeout(){},confirm(){return true},crypto:{randomUUID:()=>Math.random().toString(36).slice(2)}});
 vm.runInContext(source,ctx);
 return{el,ctx,run:s=>vm.runInContext(s,ctx),data:()=>JSON.parse(vm.runInContext('JSON.stringify(state)',ctx)),saved:()=>kv.get("cp-influencer-ux-v3")||null,toggle(id){handlers.click({target:{closest:()=>({dataset:{toggle:id},hasAttribute:()=>false})}})},submit(id){const e=el(id);(e.onsubmit||e.handlers.submit)({preventDefault(){}})}}}

let count=0;function test(name,fn){fn();count++;console.log('PASS '+name)}
const a=app();
test('initial data migrates to valid v3',()=>assert.equal(a.run('validV3(state)'),true));
test('unknown follower totals are not zero',()=>assert.equal(a.run('total(state.records[0])'),null));
test('partially known totals remain unknown',()=>assert.equal(a.run('total({channels:[{followers:100},{followers:null}]})'),null));
test('known totals sum channels including zero',()=>assert.equal(a.run('total({channels:[{followers:100},{followers:0},{followers:20}]})'),120));
test('seed names are pending review',()=>assert.ok(a.data().records.every(r=>r.status==='pending')));
test('team table contains province and platform links',()=>{assert.ok(a.el('people-rows').innerHTML.includes('facebook.com'));assert.ok(html.includes('<th>จังหวัดที่อยู่</th>'))});
test('keyword fallback does not invent parsed AI filters',()=>assert.equal(a.run('parseChips("หาเรื่องขยะ อยู่สระบุรี")[0].kind'),'keyword'));
a.run('chips=parseChips("หัวข้อ:ขยะ, จังหวัด:สระบุรี")');
test('chips are editable draft until search',()=>assert.equal(a.run('applied.length'),0));
a.submit('query-form');
test('unknown provinces fail an explicit province filter',()=>assert.equal(a.run('state.records.filter(match).length'),0));
a.run('state.records[0].serviceProvinces=["สระบุรี"]');
test('travel province can match location chip',()=>assert.equal(a.run('match(state.records[0])'),true));
a.run('applied=parseChips("หัวข้อ:ขยะ")');
test('related explains matching tags',()=>assert.equal(a.run('matchingTags(state.records[0]).join(",")'),'ขยะ'));
const id=a.data().records[0].id,pid=a.data().projects[0].id;
a.run(`setMembership(${JSON.stringify(pid)},${JSON.stringify(id)},true)`);
a.el('p-name').value='โปรเจกต์ที่สอง';a.el('p-scope').value='ร่วมงาน รวมค่าเดินทาง';a.submit('project-form');
const pid2=a.data().projects[1].id;
a.run(`setMembership(${JSON.stringify(pid2)},${JSON.stringify(id)},true)`);
test('same person belongs to multiple projects',()=>assert.ok(a.data().projects.every(p=>p.shortlist.includes(id))));
a.run(`openQuote(${JSON.stringify(pid)},${JSON.stringify(id)})`);
a.el('q-low').value='10000';a.el('q-high').value='12000';a.el('q-price').value='11000';a.el('q-source').value='หลักฐานทดสอบในหน่วยความจำ';a.el('q-date').value='2026-09-09';a.submit('quote-form');
test('confirmed prices remain isolated per project',()=>{assert.equal(a.data().projects[0].offers[id].quote,11000);assert.equal(a.data().projects[1].offers[id],undefined)});
a.run(`setMembership(${JSON.stringify(pid)},${JSON.stringify(id)},false)`);
test('removing shortlist membership preserves other project and quote history',()=>{assert.ok(a.data().projects[1].shortlist.includes(id));assert.equal(a.data().projects[0].offers[id].quote,11000)});
test('v2 migration preserves prices and scope',()=>assert.equal(a.run('(()=>{const v2=migrate({version:1,records:SEEDS.map(r=>({...r,price:9000})),shortlist:[SEEDS[0].id],campaign:"เดิม"});const v3=upgrade(v2);return validV3(v3)&&v3.projects[0].offers[SEEDS[0].id].quote===9000&&v3.projects[0].scope===v2.projects[0].brief;})()'),true));
test('invalid duplicate channel platform rejected',()=>assert.equal(a.run('(()=>{const s=structuredClone(state);s.records[0].channels.push(s.records[0].channels[0]);return validV3(s)})()'),false));
test('unsafe channel URL rejected',()=>assert.equal(a.run('(()=>{const s=structuredClone(state);s.records[0].channels[0].url="javascript:alert(1)";return validV3(s)})()'),false));
test('inverted estimates rejected',()=>assert.equal(a.run('(()=>{const s=structuredClone(state);const o=Object.values(s.projects[0].offers)[0];o.low=20000;o.high=10000;return validV3(s)})()'),false));
a.run('save()');const b=app(a.saved());
test('reload preserves v3 projects and profile data',()=>assert.deepEqual(b.data(),a.data()));
test('sidebar has only two main menu items',()=>assert.equal((html.match(/<button data-page=/g)||[]).length,2));
test('external discovery clearly disabled without backend',()=>{assert.ok(html.includes('disabled title="ยังไม่เชื่อม AI และ ScrapeCreators"'));assert.ok(!source.includes('api.scrapecreators.com'))});
const localBefore=a.saved();
a.ctx.fetch=async()=>({ok:false,headers:{get:()=> 'application/json'},json:async()=>({error:'not_configured'})});
const beforeFailure=a.data();await a.run('openTeam()');
test('unconfigured team keeps local data intact',()=>assert.deepEqual(a.data(),beforeFailure));
a.ctx.fetch=async()=>({ok:true,headers:{get:()=> 'application/json'},json:async()=>({configured:true,state:null,revision:0})});
await a.run('openTeam()');
test('empty central database has no seed profiles',()=>assert.equal(a.data().records.length,0));
a.run('state.projects[0].name="Draft";save()');
test('team draft does not replace local database',()=>assert.equal(a.saved(),localBefore));
a.ctx.fetch=async()=>({ok:false,headers:{get:()=> 'application/json'},json:async()=>({error:'conflict'})});
await a.run('pushTeam()');
test('conflict retains draft without reporting saved',()=>{assert.equal(a.data().projects[0].name,'Draft');assert.equal(a.run('teamRevision'),0);assert.ok(a.el('team-status').textContent.includes('มีคนอื่น'));});
console.log(`${count} checks passed; DOM stub, not browser rendering. Test data stayed in memory.`);
